pipeline {
  agent any

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main',
            credentialsId: 'github-creds',
            url: 'https://github.com/AnadictMathew/my-codes.git'
      }
    }

    stage('Build JAR') {
      steps {
        dir('Applications/logging-service/logging-service') {
          sh 'mvn clean package -DskipTests'
        }
      }
    }

    stage('Docker Build') {
      steps {
        dir('Applications/logging-service/logging-service') {
          sh """
            docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} .
            docker tag ${IMAGE_NAME}:${BUILD_NUMBER} ${IMAGE_NAME}:latest
          """
        }
      }
    }
  }
}