pipeline {
  agent any

  environment {
    IMAGE_NAME = "booking-service"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main',
            credentialsId: 'github-creds',
            url: 'https://github.com/AnadictMathew/my-codes.git'
      }
    }

    stage('Read Version') {
      steps {
        dir('Applications/booking-service/booking-service') {
          script {
            env.BASE_VERSION = sh(
              script: "mvn help:evaluate -Dexpression=project.version -q -DforceStdout",
              returnStdout: true
            ).trim()
            env.IMAGE_VERSION = "${env.BASE_VERSION}.${env.BUILD_NUMBER}"
          }
        }
      }
    }

    stage('Build JAR') {
      steps {
        dir('Applications/booking-service/booking-service') {
          sh 'mvn clean package -DskipTests'
        }
      }
    }

    stage('Docker Build') {
      steps {
        dir('Applications/booking-service/booking-service') {
          sh """
            docker build -t ${env.IMAGE_NAME}:${env.IMAGE_VERSION} .
            docker tag ${env.IMAGE_NAME}:${env.IMAGE_VERSION} ${env.IMAGE_NAME}:latest
          """
        }
      }
    }
  }
}