pipeline {
  agent any

  environment {
    IMAGE_NAME    = "booking-service"
    IMAGE_VERSION = "1.0"   // change to 1.1, 1.2, etc.
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main',
            credentialsId: 'github-creds',
            url: 'https://github.com/AnadictMathew/my-codes.git'
      }
    }

    stage('Build JAR') {
      steps {
        dir('Applications/booking-service/booking-service') {
          sh 'mvn clean package -DskipTests'
        }
      }
    }

    stage('Docker Build') {
      steps {
        dir('Applications/booking-service/booking-service') {
          sh """
            docker build -t ${env.IMAGE_NAME}:${env.IMAGE_VERSION} .
            docker tag ${env.IMAGE_NAME}:${env.IMAGE_VERSION} ${env.IMAGE_NAME}:latest
          """
        }
      }
    }
  }
}