pipeline {
  agent any

  environment {
    IMAGE_NAME = "booking-service"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main',
            credentialsId: 'github-creds',
            url: 'https://github.com/AnadictMathew/my-codes.git'
      }
    }

    stage('Build JAR') {
      steps {
        dir('Applications/booking-service/booking-service') {
          sh 'mvn clean package -DskipTests'
        }
      }
    }

    stage('Docker Build') {
      steps {
        dir('Applications/booking-service/booking-service') {
          sh """
            docker build -t ${env.IMAGE_NAME}:${env.BUILD_NUMBER} .
            docker tag ${env.IMAGE_NAME}:${env.BUILD_NUMBER} ${env.IMAGE_NAME}:latest
          """
        }
      }
    }
  }
}